### ISSUE TITLE
truncates text only once

### ISSUE THREAD

**Issue by tqwqt** [DiZhou92/ngx-line-truncation#15]
I have an array of text and variable 'text', that takes a value from array each animation cycle,
but text truncates only first time.
I have screenshout where you can see that hasTruncated event stopped fires.
Also I created repo with code that can reproduce my issue: [https://github.com/tqwqt/angular-line-truncation-test](https://github.com/tqwqt/angular-line-truncation-test)
<img width="820" alt="issue" src="https://user-images.githubusercontent.com/25612782/69885250-f033ee00-12e4-11ea-8b05-779124aafe9f.PNG">

**Comment by DiZhou92** [comment]
thanks i will look into this over the weekend

**Comment by DiZhou92** [comment]
HI, sorry for the delay, I had to push off this fix deadline to the end of next week.

**Comment by DiZhou92** [comment]
Hello,

Please see https://github.com/DiZhou92/ngx-line-truncation/pull/16 for detail, 
now if you provide input `watchChanges` with true, then it should does the job.

The reason for previous version not working is because I created with library with the mindset of focus on improving the performance, running a Mutation Observer on DOM element without kill it is not a good practice (imagine a case we have lots element that uses truncation, that could potentially consume lots of resources)
So I made it keeps watching the changes if you provide a flag.
let me know if there is any other issue with this tool in the future.

Hope you enjoy it,  
Di

**Comment by DiZhou92** [comment]
before I close this issue, I have a request from you, I really like your example there, can I add it to my web demo as a showcase? 
Let me know. Thank you !

**Comment by tqwqt** [comment]
@DiZhou92 , thank you for fix!
Yes, feel free to use my example
